spring:
  cache:
    redis:
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379
    password:
#    lettuce:
#      pool:
#        max-active: 7
#        max-idle: 7
#        min-idle: 2
#        max-wait: 1000ms
#      shutdown-timeout: 200ms